name: health_care
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  english_words: ^4.0.0
  
  smooth_page_indicator: ^1.1.0
  firebase_core: ^3.10.0
  google_maps_flutter: ^2.10.0
  
  intl:
  qr_flutter: ^4.1.0
  convex_bottom_bar: ^3.2.0
  intl_phone_field: ^3.2.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  pin_code_fields: ^8.0.1
  
  carousel_slider: ^5.0.0
  get: ^4.6.6
  table_calendar: ^3.1.3
  provider: ^6.1.2  # Quản lý trạng thái của ứng dụng, giúp kết nối dữ liệu giữa View và ViewModel (Model-View-ViewModel)
  http: ^1.3.0  # Gửi các yêu cầu HTTP (GET, POST, PUT, DELETE) để tương tác với server API
  shared_preferences: ^2.5.2  # Lưu trữ dữ liệu cục bộ (như token đăng nhập, cài đặt người dùng) trong ứng dụng

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
