name: health_care
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  provider: ^6.0.0
  smooth_page_indicator: ^1.1.0
  firebase_core: ^3.10.0
  google_maps_flutter: ^2.10.0
  http:
  intl:
  qr_flutter: ^4.1.0
  convex_bottom_bar: ^3.2.0
  intl_phone_field: ^3.2.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.5
  carousel_slider: ^5.0.0
  get: ^4.6.6
  table_calendar: ^3.2.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
